### ISSUE TITLE
New Feature : Site Approval Process on Site Creation and Dashboards 

### ISSUE THREAD

**Issue by sprider** [SharePoint/PnP-Partner-Pack#151]
Hi Paolo, 

Is it possible to add the following features in PnP-Partner-Pack 3.0? This way it will become like a product and anyone can use without even customizing the code.

1) Configurable labels displayed in the forms (app icon, name, footer, etc.,)
2) Site Approval Process before creating a subsite (primary and backup approvers kind of) 
3) Dashboard (My Tasks, Sites Requested, Approved, Rejected, Failed)

We are already using PnP-Partner-Pack as our bench mark :)

**Comment by sprider** [comment]
Thank you Paolo

**Comment by camiloborges** [comment]
Hello. Would it be possible to change the PnPProvisioningJobStatus field to add another status option, let's say "Waiting Approval"?

If so, we can allow an external workflow solution( Flow, Logic Apps, Webhooks, Nintex, ... to do whatever the specific implementation requires, and only when approved the status would change to Pending.

What do you think?

**Comment by camiloborges** [comment]
Hello guys. I am working on this one. should have an update and maybe a PR by mid next week

**Comment by camiloborges** [comment]
Hello.
So, I have something, but I think we are better off waiting for  #171 as the approval / post provisioning is branched from that branch.
code is https://github.com/camiloborges/PnP-Partner-Pack/tree/approval-postprocessing and there are several small changes to allow for easier integration.

@PaoloPia : Do you see problems changing PnPProvisioningStatus to a text field? 
I haven't implemented it, but this would allow integration entirely from MS flow (which doesn't currently support updating drop down fields)

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
