### ISSUE TITLE
WebJobs failing

### ISSUE THREAD

**Issue by jjcollins53** [SharePoint/PnP-Partner-Pack#160]
Both Continuous and Scheduled webjobs are failing.

Continuous jobs never save templates. Error: Unhandled Exception: Microsoft.WindowsAzure.Storage.StorageException: The remote name could not be resolved: 'xxxxxxpnppartnerpackv2.queue.core.windows.net' ---> System.Net.WebException: The remote name could not be resolved: 'xxxxxxpnppartnerpackv2.queue.core.windows.net'

Scheduled jobs (creating new site collection based on PnP-Empty-Site template): [10/06/2016 13:37:19 > 3e2a60: INFO] Applying Provisioning Template "https://xxxxxx.sharepoint.com/sites/PnP-Partner-Pack-Infrastructure/PnPProvisioningTemplates/PnP-Empty-Site.xml" to site.
[10/06/2016 13:37:20 > 3e2a60: INFO] Exception occurred: Object reference not set to an instance of an object.

Both saying configuration not properly set, but connection strings are as follows:

```
<add name="AzureWebJobsDashboard" connectionString="DefaultEndpointsProtocol=https;AccountName=xxxxxx.pnppartnerpackv2;AccountKey=Vr2+YEOhjxg9cTakVCXTnAc7si/hpjATeLTplSQtZPKPO9bUcO4JfqnBA8YtjgU0uwwHajBw5/mmqEPOXStBbg==" />
<add name="AzureWebJobsStorage" connectionString="DefaultEndpointsProtocol=https;AccountName=xxxxxxpnppartnerpackv2;AccountKey=Vr2+YEOhjxg9cTakVCXTnAc7si/hpjATeLTplSQtZPKPO9bUcO4JfqnBA8YtjgU0uwwHajBw5/mmqEPOXStBbg==" />
```

Please help.

**Comment by VesaJuvonen** [comment]
I'd double check the configuration settings from the Azure UI. You can ensure easily that the values are correct using the Azure UI, so these do not have to be included in the web/app.config files... This way you don't need to share the secret in the code, you just override the key using Azure UIs.

**Comment by PaoloPia** [comment]
Hi @jjcollins53,
Have you fixed the issue following the above suggestion? Thanks.

**Comment by PaoloPia** [comment]
Hi @jjcollins53,
In the meantime I will close this issue. Feel free to let me know if you need any further support and I will be more than happy to re-open it, if needed. Thanks.
