### ISSUE TITLE
Wot No On Premises Version

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/PnP-Partner-Pack#161]
Hi Paolo

I am dismayed to see there appears to be no On-premises version yet.

Do we have an eta for it ?

The vast majority of SharePoint customers are still using On-Premises so we really should have and On-Premises version which does not use Azure et al.

Regards

Nigel

**Comment by VesaJuvonen** [comment]
We don't have an ETA for this, since it's dependent on the community contributions.

**Comment by levesquesamuel** [comment]
Hi, I might be interested to work on an OnPrem partner pack. How would you see that? A separate partner pack or make the existing one work OnPrem and Online ? 
Regards

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
