### ISSUE TITLE
Provision-GovernanceTimerJobs.ps1 only provisions 2 jobs instead of all

### ISSUE THREAD

**Issue by rroman81** [SharePoint/PnP-Partner-Pack#162]
[Provision-GovernanceTimerJobs.ps1](https://raw.githubusercontent.com/OfficeDev/PnP-Partner-Pack/master/scripts/Provision-GovernanceTimerJobs.ps1)  seems to only deploy _EnforceAdminsJob_ and _ExternalUsersJob_ but not others.  Is that by design of the v2.0?  Am I missing a step here?  If not, I can augment the script.

**Comment by camiloborges** [comment]
Hello.
I also found the published scripts are not currently publishing all the jobs.
You can tweak the script for that, or you can use the version I am currently using to deploy them.
https://github.com/camiloborges/PnP-Partner-Pack/blob/ba2d430ae1c34aa29ecdca44163f7d62e4e41359/scripts/Provision-GovernanceTimerJobs.ps1

Please note that  the continuous job isn't added in this very commit I mentioned here, but you can by adding a new line with the following content DeployJob  "ContinousJob"

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the PnP Partner Pack. We are working on a new setup wizard (Windows OS desktop only) and we are going to evaluate and share the PR #171 from Camillo to have a fully scripted setup mainly based on AzureRM. It's a matter of time and resources. Sorry for the delay.
