### ISSUE TITLE
Bug v2.0: Can't create Subsite using default Subsite Template...

### ISSUE THREAD

**Issue by 2P2-Anthony** [SharePoint/PnP-Partner-Pack#166]
We tried to create a new subsite using the default Empty Subsite Template that comes with the tool, however it errors out after filling out and submitting the Site Configuration Form with the follow error:

```
 Error stepping through Site creation: Internal Server Error
```

I'm not sure yet if the tool is trying to create the subsite immediately or building a package for the job queue.

Either way, something's wrong when the default subsite template won't install out of the box. Where should I should start looking?

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the PnP Partner Pack. When you fill the sub-site creation form it will just enqueue a message in the blob storage queue. Then the site creation will be handled by a webjob. Are you able to create sub-sites using different templates or it is a setup issue that blocks you from creating any sub-site?

**Comment by amalbon** [comment]
Hi Paolo, after installing the Partner Pack I'm encountering the exact same issue.  

I've had a look in the Web App under WebJobs, and don't see any there (or any logs)

Any ideas on how to troubleshoot?  Thanks

**Comment by PaoloPia** [comment]
Hi,
You should be able to open the WebJobs management UI and to look into the log file, simply using the https://portal.azure.com web site and browsing for the storage account that you created during the setup process.

**Comment by amalbon** [comment]
Hi Paolo,

I've noticed that although the 'ScheduleJob' webjob is deployed in my app service, it is not visible in the Scheduler Job Collection (where you advise changing frequency to every 5 mins).

I can however see the other two scheduled jobs (CheckAdminsJob and ExternalUsersWebJob) in the Scheduler Job Collection . 

Could this be the issue and if so, is it possible to manually fix this?

**Comment by PaoloPia** [comment]
Hi, 
can you try to re-install the PnP Partner Pack using the new Setup Wizard that we released in DEV (still under preview) a few days ago? Thanks.

**Comment by PaoloPia** [comment]
Hi,
Do you have any new feedback about this issue? Or can I assume that you solved it and close this item? Thanks.

**Comment by amalbon** [comment]
Hi, will try reinstalling this week and come back to you. Thanks

**Comment by PaoloPia** [comment]
Hi,
I don't see any feedback on this item in the last 30 days. Thus, I will close it. In case of any further need, please let me know and I will be more than happy to re-open this item. Thanks.
