### ISSUE TITLE
Exception Occurred: composed look 'SharePointBranding' 

### ISSUE THREAD

**Issue by wukimus** [SharePoint/PnP-Partner-Pack#178]
I am getting this error basically its saying it cant find a composed look called 'SharePointBranding'. Of course the error only occurs when I turn on Apply Tenant Branding. Any ideas why this was not provisioned when I ran Provision-InfrastructureSiteArtifacts powershell script

**Comment by LeoGoGarcia** [comment]
+1

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the PnP Partner Pack. Could you please give me much more details about the context? Are you creating a new site collection or a site?  Have you configured the tenant branding before activating that function? Thanks.

**Comment by PaoloPia** [comment]
Hi,
I will close this item, because you did not provided any answer after about two months. In case of any further need, let me know and I will be more than happy to re-open the issue. Thanks.
