### ISSUE TITLE
UI-Based Desktop Setup Application?

### ISSUE THREAD

**Issue by kierer** [SharePoint/PnP-Partner-Pack#179]
There's a mention of a UI-based app for Partner Pack management in the ReadMe : "Notice that the UI based desktop Setup application (for Windows OS only) that will be released **pretty soon**". 

Might one of the contributors have a sense for how far off a beta or release might be? We've been pondering rolling our own List schema management tool for managing diffs against a target schema and applying changes across hundreds or thousands of managed site deployments in addition to managing branding. The current manual deployment process for the Partner Pack involves a good bit of overhead, but a pre-built setup application would make leveraging the Partner Pack for some of our scenarios more appealing. Thanks in advance.

**Comment by PaoloPia** [comment]
Hi,
We're working on it during these day. It shouldn't take long to release it, but I cannot make any promise. Thanks for your patience.
