### ISSUE TITLE
V2.0 (Nov-16) certificate issue

### ISSUE THREAD

**Issue by LateNightDBA** [SharePoint/PnP-Partner-Pack#183]
Following deployment guide (twice) second time very carefully. Certificates and thumbprints recorded and entered where required. starting application following error occurs.
----------------
Oops! Exception occurred!
Value cannot be null. Parameter name: certificate 

More details
at Microsoft.IdentityModel.Clients.ActiveDirectory.ClientAssertionCertificate..ctor(String clientId, X509Certificate2 certificate) at OfficeDevPnP.Core.AuthenticationManager.GetAzureADAppOnlyAuthenticatedContext(String siteUrl, String clientId, String tenant, X509Certificate2 certificate, AzureEnvironment environment) ........

------------------------
Not sure where one should be looking to resolve.
Many thanks for the great tool as it holds many great promises. I really wish to get this corrected.

**Comment by camiloborges** [comment]
Hello.
I believe I've seen this issue in few different scenarios:
If you are running it from a published azure services:
- Multiple Certificates with the same name registered in the Azure Service. 
Make sure you only have one.  (AppServices ->You App service -> SSL Certificates)

- Partner Pack Web.Config wasn't updated with the correct settings 
check it via: https://<contoso>.scm.azurewebsites.net/dev/wwwroot/Web.config

You are looking for the TenantSettings:
```Xml
 <TenantSettings tenant="kasa.onmicrosoft.com" appOnlyCertificateThumbprint="481178B21627B782B3834E9A51FACE83649577F5" infrastructureSiteUrl="https://kasa.sharepoint.com/sites/PnP-Partner-Pack-Infrastructure" useApproval="true" usePostProvisioning="true" />
   
if you are running locally. 
- Try running VS as admin.
- I think current master branch removes the self signed certificate from your personal certificate store. Make sure you have the certificate loaded. It is a little hard to debug this as the method [that loads the certificate ](https://github.com/SharePoint/PnP-Partner-Pack/blob/bb3e78d520b155420a330c484752df03625f33da/OfficeDevPnP.PartnerPack.SiteProvisioning/OfficeDevPnP.PartnerPack.Infrastructure/PnPPartnerPackSettings.cs#L29)runs within a Lazy<> call.

**Comment by LateNightDBA** [comment]
Many thanks for the reply.
I was being stumped on a couple of issues and now resolved.
Firstly – editor being used (Notepad ++) inserted characters into the certificate signature when saving and uploading.
Secondly, as this is being performed with low level Azure subscription, the app service kept “bouncing” down from basic to a shared pricing tier and therefore not supporting the certificate as outlined in the install document. 
Lastly, getting the schedule web jobs to work, setup within the webjob also required similar setup as outlined for app settings around WEBSITE_LOAD_CERTIFICATES with a value of ‘*’

Issue closed.

Regards.

**Comment by camiloborges** [comment]
Hello. Just realized something. 
You might need few more app settings for the provisioning to work.
have a look at the dev branch doco.
https://github.com/SharePoint/PnP-Partner-Pack/blob/dev/Documentation/Manual-Setup-Guide.md#app-only-certificate-configuration-in-the-azure-app-service
