### ISSUE TITLE
Again: Value cannot be null. Parameter name: certificate

### ISSUE THREAD

**Issue by MelAtWork** [SharePoint/PnP-Partner-Pack#184]
I do have the error of the missing certificate.
I was reading through about around 10 Blog entries and solution suggestions but still cannot fix it.
I will provide you all the detail, maybe someone has another hint for me.

This is the exception message:
![pnp_ex](https://cloud.githubusercontent.com/assets/11026615/20965193/dedbcebc-bc74-11e6-9c1f-bb22e47f0665.png)

I followed these instructions:
https://github.com/SharePoint/PnP-Partner-Pack/blob/master/Documentation/Manual-Setup-Guide.md

The certificates, keyCredential section and the configuration for web.config where generated with the provided pnp scripts.

I created the infrastructure site collection manually because the cmdlets changed from "SPO" to "PNP" and there were no aliases found .... but I don't think the infrastructure site has anything to do with this certificate issue.

From what I read in other posts concerning this issue I did the following:
- I checked the thumbprint of my .cer file several times - made sure to read it with powershell because of hidden characters and so on... 
- I made sure that there are no other certificates with the same name in my Azure that is hosting the code
- I double and triple checked the configuration in the web.config file of the application with all needed values and the manifest file. 

Is it correct that if I download the manifest again (or view it in the browser) after setting the keyCredentials, the value in the keyCredentials is shown as null? Because of security reasons, I guess. This is how it looks like in the browser.... when uploading it the value had a very long string of course and was not null.

![keycreds](https://cloud.githubusercontent.com/assets/11026615/20965819/d301a208-bc77-11e6-9f59-edda024bcb56.png)

- I unchecked that checkbox ("Activate original Authentication" or something like that) when publishing

What will be maybe important:
- The Application and Blob Storage is hosted in my azure for testing, that is running with the credits of my MSDN subscription
- The Azure AD and O365 Tenant are running in a second subscription (our o365 environment for testing purposes but with fully paid subscriptions)

But from what I read, this should not be a problem usually, am I right here?
Unfortunately I have no clue how I coud proceed to find the issue.

**Comment by jkovach82** [comment]
+1 on this thread, I am having the same problem.

**Comment by jkovach82** [comment]
Got it working... I had forgotten to add the WEBSITE_LOAD_CERTIFICATES * configuration in App Settings.

![image](https://cloud.githubusercontent.com/assets/20099972/21019052/06e59f14-bd24-11e6-9de8-e34f1416c594.png)

**Comment by PaoloPia** [comment]
Hi @MelAtWork,
Have you tried the above solution?
Thanks,
Paolo

**Comment by PaoloPia** [comment]
Hi @MelAtWork,
In the meantime I will close this issue. Feel free to let me know if you need any further support and I will re-open it, if needed.
