### ISSUE TITLE
PnP Templates Gallery Issue

### ISSUE THREAD

**Issue by jkovach82** [SharePoint/PnP-Partner-Pack#188]
I am unable to find any of the templates listed on the website here: https://dev.office.com/blogs/pnp-templates-gallery-open-source-provisioning-templates

According to the screenshot I should be able to search for "curriculum" and pull up that template however nothing is return. However, when I search for just one letter "c" or the word "template" I do get a bunch of templates named "template".  Whats going on here?

![image](https://cloud.githubusercontent.com/assets/20099972/21031943/24f6e7c4-bd5b-11e6-854e-62d48eaa76fc.png)

![image](https://cloud.githubusercontent.com/assets/20099972/21031996/693299d8-bd5b-11e6-8677-632de5b738bb.png)

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the PnP Partner Pack. I suppose that you are using an old version of the web.config file of the PnP Partner Pack, which targets the testing environment of the PnP Templates Gallery. Please double-check your web.config and see if it targets the right URL. It should be like this one:

https://github.com/SharePoint/PnP-Partner-Pack/blob/master/OfficeDevPnP.PartnerPack.SiteProvisioning/OfficeDevPnP.PartnerPack.SiteProvisioning/Web.config#L51

Thanks.
