### ISSUE TITLE
The remote server returned an error: (401) Unauthorized.

### ISSUE THREAD

**Issue by nikhilsarvaiye** [SharePoint/PnP-Partner-Pack#193]
`at System.Net.HttpWebRequest.GetResponse() at Microsoft.SharePoint.Client.SPWebRequestExecutor.Execute() at Microsoft.SharePoint.Client.ClientContext.GetFormDigestInfoPrivate() at Microsoft.SharePoint.Client.ClientContext.EnsureFormDigest() at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery() at OfficeDevPnP.PartnerPack.SiteProvisioning.Controllers.HomeController.Index() at lambda_method(Closure , ControllerBase , Object[] ) at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End() at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End() at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)

{
x-ms-diagnostics: 3001000;reason="There has been an error authenticating the request.";category="invalid_client"
SPRequestGuid: 9d92c09d-c08a-3000-bc79-53302afcd118
request-id: 9d92c09d-c08a-3000-bc79-53302afcd118
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
SPRequestDuration: 86
SPIisLatency: 2
MicrosoftSharePointTeamServices: 16.0.0.6001
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
Content-Length: 453
Date: Tue, 13 Dec 2016 07:02:04 GMT
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
Server: Microsoft-IIS/8.5
WWW-Authenticate: Bearer realm="bdc08e7e-9016-4d3c-bcc0-23bb416948a0",client_id="00000003-0000-0ff1-ce00-000000000000",trusted_issuers="00000001-0000-0000-c000-000000000000@*,https://sts.windows.net/*/,00000003-0000-0ff1-ce00-000000000000@90140122-8516-11e1-8eff-49304924019b",authorization_uri="https://login.windows.net/common/oauth2/authorize"
X-Powered-By: ASP.NET
}
`

I am facing this, I have done app registration, and everything from the New Portal
I have all the full rights for both on Sharepoint Tenant and Azure

Not sure What I am missing,

Below link gives me some thing,
https://social.msdn.microsoft.com/Forums/en-US/ee56d4b6-45f4-4404-8920-ca63c6f8f415/got-3001000reasonthere-has-been-an-error-authenticating-the-requestcategoryinvalidclient?forum=WindowsAzureAD

**Comment by rickenberg** [comment]
Just wondering - did you assign the Azure AD application permissions to Office 365 SharePoint Online as application (not delegated) permissions as described in the setup guide? In case you changed from delegated to application permissions - did you recycle the application pool of the web site after the change, because auth tokens are cached there.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the PnP Partner Pack. I would suggest you to follow step by step the setup guide (https://github.com/SharePoint/PnP-Partner-Pack/blob/master/Documentation/Manual-Setup-Guide.md) or the setup video (https://www.youtube.com/watch?v=ezWYorZClTI&feature=youtu.be).
Unfortunately I cannot figure out what you missed during the setup process, but looks like an issue related to the app registration in Azure AD.
I will close this item, which is not related to a product issue/bug, rather to a wrong setup procedure.

**Comment by nikhilsarvaiye** [comment]
Hi rickenberg,
I was not able to resolve that issue.
Looked like it was only coming on specific environment, and setting up everything using main admin(main global admin) resolved issue.
