### ISSUE TITLE
SaveSiteAsTemplate Back button not working properly

### ISSUE THREAD

**Issue by biste5** [SharePoint/PnP-Partner-Pack#196]
Type: Bug

Tested on:
SharePoint Online

Latest branch commit: 
[dc9ce](https://github.com/SharePoint/PnP-Partner-Pack/commit/dc9ce6ee78c85a8c2198f934870d4c666ffe1246)

Issue description:
On the partial view _SaveSiteAsTemplate.cshtml_ the fuctionality of _Back_ button isn't working as expected.
It causes a page post back, and behaves exactly the same as _Save_ button.
Validation still does occur when pressing _Back_ button, and if mandatory fields are filled in, it will schedule job for template extraction.

Expected behavior:
Button shouldn't cause any validation
Button should redirect to previous page (normally is Site Settings page, where the link to 'Save this site as provisioning template' is pushed

**Comment by PaoloPia** [comment]
Hi Massimo,
This issue has been fixed within PR #199. Thanks for your feedback.
