### ISSUE TITLE
Documentation Correction

### ISSUE THREAD

**Issue by ehalsey** [SharePoint/PnP-Partner-Pack#204]
Then, provide a name for your application (we suggest to name it "SharePoint PnP Partner Pack"), select the option "Web app / API", and **fill in the "Sign-on URL" with the URL of the Azure Web App that you will create (in one of the following steps)**. Click create when done.

Maybe it's just me but fill in the url of the Azure Web Appp that you will create (in one of the following steps) does not make sense.  How can you fill it in if it hasn't been created?

**Comment by amalbon** [comment]
I noticed this too, it's actually referring to the URL of the previously created Web App

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. I've just fixed the documentation.
