### ISSUE TITLE
Missing "Save Site as Provisionning Template" and "Add new site"

### ISSUE THREAD

**Issue by ypcode** [SharePoint/PnP-Partner-Pack#207]
Hi,

Since 'Sharing is Caring', I propose the solution of an already fixed issue I encountered:

I was missing two on the main features of the PnP Partner pack:
- Save site as provisionning template
- New subsite redirection to PnP Partner Pack

Since they are JS customisations, a quick look in the JS console gives the following message:
settings.aspx:174 Mixed Content: The page at 'https://xxxdev.sharepoint.com/sites/Workspaces/template/_layouts/15/setti…sharepoint%2Ecom%2Fsites%2FWorkspaces%2Ftemplate%2FSitePages%2FHome%2Easpx' was loaded over HTTPS, but requested an insecure script 'http://xxxpack-dev.azurewebsites.net/Templates/Overrides/PnP-Partner-Pack-Overrides.js?rev=457cefaa69cc4d6d9d37cecc6cb04dc3'. This request has been blocked; the content must be served over HTTPS.
(anonymous) @ settings.aspx:174

It is, indeed a misconfiguration issue, as -AzureWebSiteUrl argument of the Provision-InfrastructureSiteArtifacts.ps1 script, I gave my azure web site URL but in HTTP and not HTTPS.
To fix it :
- Re-run the PowerShell script with the proper argument (httpS://...)
- Reactivate the PnP Partner Pack from the settings page of the application (The upper-right link)

If anyone runs into the same issue, I hope he/she will be helped by this post.

@PaoloPia, maybe it could be emphasized in the setup procedure (even if I admit it was a silly misconfiguration).

Best regards,
Yannick

**Comment by VesaJuvonen** [comment]
thx Yannick, we'll get this clarified in the docs. Good input.

**Comment by PaoloPia** [comment]
Thank you Yannick! We will make it much more clear in the docs, and however a couple of days ago we released in preview, within the DEV branch, a new setup wizard that does almost everything for you. I will close this item.
