### ISSUE TITLE
Connect-SPOnline to  Connect-PnPOnline

### ISSUE THREAD

**Issue by rossotti** [SharePoint/PnP-Partner-Pack#209]
I ran into issues with Provision-InfrastructureSiteArtifacts script.  After some searching, I replaced several cmdlets in the script such as Connect-SPOnline to Connect-PnPOnline.

I think I have it working now after some of these changes.  Will the scripts be updated to reflect the new cmdlet names or did I do something else wrong?  

http://www.erwinmcm.com/the-case-of-get-sposite/

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the PnP Partner Pack. You're right and we are going to update all the scripts. I will close this item.

**Comment by bmomtschilow** [comment]
It still uses SPOnline
