### ISSUE TITLE
Unable to use PNP gallery templates

### ISSUE THREAD

**Issue by SP2017** [SharePoint/PnP-Partner-Pack#211]
using a local template from the infra site coll works fine to create a site, but when selecting a template from the PNP gallery site, i get an error stating "System.IO.IOException: Cannot open package because FileMode or FileAccess value is not valid for the stream."
when i look at the urls of the templates in the preview screen source, i see addresses like "https://pnptemplatesgallery.blob.core.windows.net/templates-201611251509/RootFolder/Human%20Resources/CV-Database/CVDatabase.pnp" however this cannot be retrieved ("ResourceNotFound")

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the PnP Partner Pack. We fixed this issue just a couple of weeks ago, and you will find it in the next master merge.
