### ISSUE TITLE
ContiniousJob Code not available

### ISSUE THREAD

**Issue by vgarikpa** [SharePoint/PnP-Partner-Pack#213]
Hello Paolo,
I am unable to find continuous job code in partner pack. Is it going to be introduced as an enhancement?

**Comment by biste5** [comment]
Hi, I'm not Paolo :)

ContinousJob project is here
https://github.com/SharePoint/PnP-Partner-Pack/tree/master/OfficeDevPnP.PartnerPack.SiteProvisioning/OfficeDevPnP.PartnerPack.ContinousJob

Anyway most of the implementation code is part of the Infrastructure project
https://github.com/SharePoint/PnP-Partner-Pack/tree/master/OfficeDevPnP.PartnerPack.SiteProvisioning/OfficeDevPnP.PartnerPack.Infrastructure/Jobs

**Comment by VesaJuvonen** [comment]
I'm not Paolo either, but closing issue, since answered.
