### ISSUE TITLE
Support for multi-lingual UI

### ISSUE THREAD

**Issue by biste5** [SharePoint/PnP-Partner-Pack#214]
**Type**
Enhancement

**Description**
At least the UI for Site creation should be localized in the language of the SP site where PnP Partner Pack is installed, and started from

**Comment by biste5** [comment]
I've been already started working on this implementation, using .NET RESX files.
So, I'll issue (likely today) a work in progress PR, where I'll add these I've already implemented.

It will contain:
- RESX files for Dutch, English, Italian
- Localization of labels in Site Creation UIs

**Comment by VesaJuvonen** [comment]
Hi Massimo, that would be excellent change and improvement. Absolutely welcome.

**Comment by PaoloPia** [comment]
Hi Massimo,
while waiting for your updated PR, I will close this issue, which is not needed anymore. Thanks.
