### ISSUE TITLE
ExtensibilityHandler not called correctly from Partner Pack (sub site creation)

### ISSUE THREAD

**Issue by biste5** [SharePoint/PnP-Partner-Pack#215]
**Type**
Bug

**Description**
I have written an 'extensibility handler' for PnP Provisioning Templates Engine. It behaves as expected when instantiated from, for instance, a console application. It doesn't work as expected when applied by ContinousJob as Partner Pack implements.
The issue is that my override of `Provision` method in the second case receives a ClientContext set to the host web, instead of the newly created web. And doesn't seem there's very easy way to retrieve a reference to the sub web either.

I haven't tested the behavior of site collection creation from Partner Pack, in combination with using my custom handler

**Comment by biste5** [comment]
The issue it's actually in PnP Sites Core, and I reported it there
https://github.com/SharePoint/PnP-Sites-Core/issues/1014

**Comment by PaoloPia** [comment]
Hi Massimo,
Actually, having an extensibility provider in place is not a scenario covered by the PnP Partner Pack. We can work on it, but it is not supposed to be covered by the current implementation. I will mark this item as an "enhancement". Thanks.

**Comment by biste5** [comment]
Hi Paolo,

well, that's just a feature that Partner Pack gets directly from PnP Provisioning Engine. And in this case it inherits the bug ;) (or is it a feature?)

Massimo

**Comment by leedale1981** [comment]
Hi biste5,

I have implemented something similar in an extensibility handler using the `IProvisioningExtensibilityHandler` interface. 

Even though the ClientContext isn't the newly created web you get access to the newly created web information through the ProvisioningTemplate object that gets passed to this function.

For example you can do the following:

```
string newWebTitle = template.WebSettings.Title;
string newWebUrl = template.Parameters["RelativeUrl"];
```

**Comment by leedale1981** [comment]
Hi biste5,

I have a solution for how to get the web context of the newly created web inside the `IProvisioningExtensibilityHandler` You can use the provisioning engine tokens specified [here](https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/ProvisioningEngineTokens.md) to pass configuration data to your handler. 

So inside your template you can use a token like so:

```
<pnp:Providers>
     <pnp:Provider>
          <pnp:Configuration>
            <Config xmlns="http://schemas.com/emailextensibilityprovider">
              <newSiteUrl>{site}</newSiteUrl>
            </Config>
          </pnp:Configuration>
        </pnp:Provider>
      </pnp:Providers>
```

You can then access this site value inside your provision function which will be populated with the newly created web URL.

```
            XNamespace ns = "http://schemas.com/emailextensibilityprovider";
            XDocument doc = XDocument.Parse(configurationData);
            var newWebUrl = doc.Root.Descendants(ns + "newSiteUrl").FirstOrDefault().Value;
            newWebUrl = ctx.Url + newWebUrl.Replace(ctx.Web.ServerRelativeUrl, "");
```

You could then new up a new ClientContent with the web URL.

`ClientContext webClientContext = ctx.Clone(newWebUrl);`

**Comment by PaoloPia** [comment]
The fix proposed by Luis has just been merged. I will close this item. Thanks.
