### ISSUE TITLE
Provisioning Job Status is Failed in PnPProvisioning Library but site collection is still created

### ISSUE THREAD

**Issue by sscanl01** [SharePoint/PnP-Partner-Pack#218]
When I create a site collection using the empty default template I can see the entry added to the PnPProvisioning library, at first the status is pending then after a few minutes it changes to running and then to failed. However, when I check the SharePoint Admin centre I can see the new site collection has been created and I can access this with no issues so to me it looks like nothing has failed. 
When I look back at the library the column called Provisioning Job Error states "Operation is not valid due to the current state of the object". Can anyone please advised what could be causing this error message when in actually fact I cant see anything wrong with the site. 

Thanks,
![pnp status issue](https://cloud.githubusercontent.com/assets/23316462/22311535/c0f178fe-e34b-11e6-90a8-af9fb01d674f.JPG)

**Comment by camiloborges** [comment]
Hello.
Have you set the application variables that increase the timeout?

**Comment by sscanl01** [comment]
As I am not 100% sure what you mean I will say no I haven't, where exactly is this set?

Thanks,

**Comment by camiloborges** [comment]
Hello.
Sorry, could and should had given a better answer.
https://github.com/SharePoint/PnP-Partner-Pack/blob/master/Documentation/Manual-Setup-Guide.md#apponlywebapp
Check the following :
After that, scroll a little bit to the "Application Settings" section. There, you will have to configure the following settings:

WEBSITE_LOAD_CERTIFICATES with a value of *;
WEBJOBS_IDLE_TIMEOUT with a value of 10000;
SCM_COMMAND_IDLE_TIMEOUT with a value of 10000;

Camilo Borges

Sent via iPhone while out and about

**Comment by joelfmrodrigues** [comment]
Hi @camiloborges I have the same error an I've set the app variables.

**Comment by sscanl01** [comment]
Thanks @camiloborges I didnt actually have the below 2 settings:
WEBJOBS_IDLE_TIMEOUT with a value of 10000;
SCM_COMMAND_IDLE_TIMEOUT with a value of 10000;

I have added these retried and now getting a different "Provisioning Job Error" which is:

Composed look "SharePointBranding" can not be found; pass null or empty to set look directly (not based on an existing entry). 

![newerrormessage](https://cloud.githubusercontent.com/assets/23316462/22331773/1c563cf6-e3c5-11e6-96e1-2cc50088fb83.PNG)

**Comment by sscanl01** [comment]
Ok so I have it working now just needed to turn off tenant Branding when filling in the form when creating the site collection. @camiloborges thanks again for your help on this.
I have another question not sure if it is better opening another thread but is there any information on the ExternalUsersJob (Azure Web Job). I have published it and can see it in Azure but after running it not sure what to expect. All I know is that it checks external users. I have a requirement where a process is automated which sends a report once a month to each Site Collection Admin providing a list of all external users for that site, I am wondering could this facilitate that? 

Thanks,

**Comment by sscanl01** [comment]
I have managed to change the report frequency on the External users job, all is now working perfect. 
Thanks for the help.
