### ISSUE TITLE
The fully qualified file name must be less than 260 characters

### ISSUE THREAD

**Issue by johnbrice** [SharePoint/PnP-Partner-Pack#229]
NuGet Package restore failed for project OfficeDevPnP.PartnerPack.ScheduledJob: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters..

This was working fine on Friday. Anyone having this issues when building?

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the PnP Partner Pack. I suggest you to download the source code in a path that has a short name. Otherwise the max path length issue can occur. I already saw it in the past. I will close this item. Thanks.
