### ISSUE TITLE
Does not create Scheduler Webjobs

### ISSUE THREAD

**Issue by jdtoth** [SharePoint/PnP-Partner-Pack#233]
I've published both the Scheduled and Continuous Azure WebJobs via Visual Studio. Both complete successfully without error. But nothing is created in Azure under "Scheduler Job Collections". As per the instructions I shouldn't have to create it manually., should I?

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the PnP Partner Pack. I confirm that you have to schedule the ScheduledJob manually.
