### ISSUE TITLE
How to assign different PNP Permissions to users

### ISSUE THREAD

**Issue by sogrjp** [SharePoint/PnP-Partner-Pack#238]
How can I assign the different permissions to users to enter the pnp application ???
I created in Office365 4 users and assigned them to the different permissions groups of the Infrastructure Site (viewers, members, owners and visitors) but when trying to enter the PNP Application with one of these users I get the following message:
This application requires application permissions to another application. Consent for application permissions can only be performed by an administrator. Sign out and sign in as an administrator or contact one of your organization's administrators.

I have tried to give permissions to some of the users in Azure AD / PNP Application Registers but I have not been able to access with that user in the PNP Application

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the PnP Partner Pack. Right now, the application doesn't have an authorization model. If you like, you can add it and make a Pull Request to submit your changes. I will close this item, but feel free to ask any further question. Thanks.
