### ISSUE TITLE
Templated Sites Quick Launch Navigation Duplicated

### ISSUE THREAD

**Issue by LAILNZ** [SharePoint/PnP-Partner-Pack#244]
![2017-03-19_21-43-20](https://cloud.githubusercontent.com/assets/26518494/24079453/4b0a5f86-0ced-11e7-91ad-08902ebfe598.png)

Strange issue and wondering why this is occuring? I have created a blank team site and then created a document library and added it to the quick launch. Then templated the site using pnp save site as template.

Then I created a site collection from this template and all the quick launch navigation has been duplicated - see image. Any ideas why this is occuring?

**Comment by mrzyko** [comment]
We are experiencing the same behavior on our templates. I'm guessing its because the generated template from "save site as provisioning template" generates the navigation elements as RemoveExistingNodes="false". 
![image](https://cloud.githubusercontent.com/assets/24684259/24357287/74c81956-12fd-11e7-9020-02b052e8a5e7.png)

**Comment by mrzyko** [comment]
A quick fix is to go to your template site, go to Site settings > Look and Feel, remove all the navigation nodes from Quick launch (Home, Notebook, Documents, Pages, Site contents) and Top link bar (Home) and then regenerate the template. That way, the navigation nodes that are generated automatically by the STS#0 wont be created twice. 
I guess another way is to manipulate the .pnp file and set the RemoveExistingNodes to true or remove the nodes from the xml template file.

**Comment by PaoloPia** [comment]
Hi,
Yes, as stated in the previous comment, you should set the RemoveExistingNodes attribute to true.

**Comment by msm8504** [comment]
How do you edit a .pnp file to set the RemoveExistingNodes attribute to true?

**Comment by msm8504** [comment]
I was able to solve this by adding a ClearNavigation parameter to the Apply-PnPProvisioningTemplate

**Comment by PaoloPia** [comment]
Hi,
We added the behavior (ClearNavigation) by default to the April 2017 release of the PnP Partner Pack. I will close this item, as it is now solved. Thanks.
