### ISSUE TITLE
Create-SelfSignedCertificate.ps1 failing

### ISSUE THREAD

**Issue by baldswede** [SharePoint/PnP-Partner-Pack#249]
Hello, I've just started trying to install the partner pack. In the first step, when creating a self-signed certificate, your script throws the error:

> Export-PfxCertificate : The term 'Export-PfxCertificate' is not recognized as the name of a cmdlet, function, script file, or operable program.

Googling reveals that this cmdlet is a part of the Microsoft.PowerShell.Security module installed by Windows Management Framework 4.0. I have a later version installed - 5.0 - and that cmdlets seems to be missing. [Here is a list of cmdlets included in the latest version of Microsoft.PowerShell.Security](https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.security/microsoft.powershell.security)

Export-PfxCertificate is not on that list.

I used makecert.exe but I wanted you to be aware of this issue in case other users use WMF 5.x.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. I would suggest you to use the setup wizard, instead of the manual setup process. Within the setup wizard we create the X.509 certificate for you by code.
