### ISSUE TITLE
Errors after installation

### ISSUE THREAD

**Issue by baldswede** [SharePoint/PnP-Partner-Pack#250]
I have gone through the installation manual using the PowerShell scripts included in the repo.

When provisioning the infrastructral site collection, the script throws an error which seems to be caused by the provisioning engine:

> PS>.\Provision-InfrastructureSiteArtifacts.ps1 -InfrastructureSiteUrl https://[tenant-url]/sites/PnP-Partner-Pack-Infrastructure -AzureWebSiteUrl http://[web app url]/
> Apply-PnPProvisioningTemplate : The remote server returned an error: (500) Internal Server Error.
> At C:\git\PnP-Partner-Pack\scripts\Provision-InfrastructureSiteArtifacts.ps1:81 char:5
> +     Apply-PnPProvisioningTemplate $basePath\Templates\PnP-Partner-Pac ...
> +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], WebException
>     + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate
> 
> Setting content type on PnP-Empty-Site.xml
> Setting content type on PnP-Empty-Sub-Site.xml
> Setting content type on SPO-CustomBar.xml
> Setting content type on PnP-Partner-Pack-Infrastructure-Jobs.xml

Should I check if something is missing from the infrastructure site?

After that everything went smoothly.

When loading the app, everything looks OK, but when I click on "Settings" in the top right corner I get the following error:

> Oops! Exception occurred!
> Current site is not a tenant administration site.
> at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream) at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse() at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb) at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery() at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery() at
> ...

I'm not sure what this means. We are using the DvNext service with multiple host names for our site collections, so perhaps that is messing with the Partner Pack.

Furthermore, where can I find the "Save site as template" and "Create subsite" options? Do I need to enable something on the site collections where I want this functionality? The main reason we want to use the Partner Pack is to create custom subsites in some of our organizational site collections.

Thanks!

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the PnP Partner Pack. In order to setup the project, I suggest you to use the new Setup Wizard that we released last month, instead of the manual setup process.
Moreover, the "Save Site as Provisioning Template" and the new "Create SubSite" are available if you enable the PnP Partner Pack extensions (Settings menu of the PnP Partner Pack).

**Comment by PaoloPia** [comment]
Hi,
Have you managed to setup the PnP Partner Pack or are you still experiencing any issue? Can I close this item? Thanks.

**Comment by baldswede** [comment]
Hello, sorry for the late reply.

Since I'm working in a large organization with custom domains and host named site collections in Office 365 DvNext, we had to make several modifications to the Partner Pack in order for it to work in our environment.

So this issue was a bit premature as it was really no error in your code but rather that the code is written for multi-tenant/sharepoint.com customers.

Thanks.
