### ISSUE TITLE
Automated setup not accepting MS azure login credentials

### ISSUE THREAD

**Issue by amirkhanRC** [SharePoint/PnP-Partner-Pack#251]
Hi there,

I'm failing to login to MS azure subscription via the setup tool:

![image](https://cloud.githubusercontent.com/assets/20151481/24406039/35e7d030-13c7-11e7-9ed4-1bfe32be0397.png)

Error I receive is:
Additional technical information: 
Correlation ID: 734cf80f-20b4-4689-9568-2dd8eea3b5c8 
Timestamp: 2017-03-28 12:53:04Z 
AADSTS50020: User account 'amir.khan@rapidcircle.com' from identity provider 'live.com' does not exist in tenant 'Default Directory' and cannot access the application '2f86285f-33b3-4139-aacf-35c5f0d6d5d3' in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account. 

which tenant does my account need to be added as an external user? And why?

**Comment by daniel-leibold** [comment]
I got the same issue. If you already have an azure subscription link it to your Office 365 tenant. (see https://docs.microsoft.com/en-us/azure/billing/billing-add-office-365-tenant-to-azure-subscription#link-office-365-tenant-to-azure-subscription)

**Comment by PaoloPia** [comment]
Hi,
As suggested in the previous comment, it looks like your Live user's account is not configured in the Office 365 tenant.

**Comment by amirkhanRC** [comment]
Unfortunately, I'm still stuck on this error. I've
- associated the o365 tenant in my azure subscription
- changed the directory associated with the subscription
but no luck
- added my live account as an external global admin to to the o365 tenant

paolo, how come this requirement is not in the setup wizard video? nor do I find it in the manual steps.

well, any tips or help are most welcome at this point.
Amir

**Comment by amirkhanRC** [comment]
One of my colleagues helped me to overcome this particular issue.  For the the Azure login if I provide personal account that shares the email address with a work account then this error occurs.
To overcome it then, we created a new account in the personal azure subscription, made it global admin and logged on with that account.
the setup the didnt fail at login, prompted me for consent, and proceeded to create the infra site collection. 
However it did fail directly after that stating
"The user or administrator has not consented to the application with ID 'b0349a49e....' 
what additional consent is needed and how can we ensure this is provided?

**Comment by daniel-leibold** [comment]
For me it helped to "step back" and verify the Azure and Office 365 Subscription settings before starting the wizard. Ensure to "connect" your O365 Tenant with your Azure Subscription, so that you can login with your azure user to the O365 tenant. Once it is connected you should only manage users in Azure AD. 
The O365 Admin should also be able to login to the azure portal without any trouble.
In case you have "misconfigured" your Azure subscription you might also consider to create a MS Ticket in your azure portal.

**Comment by amirkhanRC** [comment]
Thanks Daniel. 

this is most likely the issue. Was able to make the setup work in a demo tenant and my live account azure subscription following these instructions:
https://docs.microsoft.com/en-us/azure/billing/billing-add-office-365-tenant-to-azure-subscription

complications arose due to the what that I have a organizational account that uses the same email address. so I had to a new account to in my personal subscription and make that the service admin

Now onto installing this in a client environment where I hope we will not run into the same issues as long as the admins have linked the o365 AAD to their Azure subscription.
Lets see,

**Comment by PaoloPia** [comment]
Hi,
Do you have any feedback about the setup process? About the issue related to the personal account with the same email of a work or school account, yes unfortunately it is a potential issue.

**Comment by PaoloPia** [comment]
Hi,
based on the fact that I don't see any further feedback on this thread since 4 weeks ago, I will close this item. If you're still experiencing any issue, please let us know and I will be more than happy to open the issue again. Thanks.

**Comment by MarinoValentino** [comment]
Dear Paolo,
had exactly yesterday this Issue during my first Partner Pack installation. I think it's still an Issue for those with the same email domain for a LiveID and Work-Accounts Azure account.
Thanks

**Comment by PaoloPia** [comment]
Hi Marino,
I'm sorry but the issue related to having a Live Account with the same email address of a Work and School account is beyond the PnP Partner Pack capabilities. Please refer to this article for further details about the Microsoft's roadmap on this topic: https://blogs.technet.microsoft.com/enterprisemobility/2016/09/15/cleaning-up-the-azure-ad-and-microsoft-account-overlap/

Thanks.
