### ISSUE TITLE
Include Managed metadat fields in PnP Partner Pack SiteProvisioning 

### ISSUE THREAD

**Issue by khannsh** [SharePoint/PnP-Partner-Pack#252]
Hi,

I am updating partnerpack to include managed metadata fields on the Site Configuration section but it is not working. Please help how to include managed metadata fields on the PnP partner pack pages. Please treat it as urgent request.

Thanks & Regards

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the PnP Partner Pack. Can you provide more details about what you want to do? Thanks.

**Comment by slackeramit** [comment]
You can integrate code from this project:
https://github.com/SharePoint/PnP/tree/dev/Samples/ECM.MVCTaxonomyPicker/

We have done it and it works perfectly.

**Comment by khannsh** [comment]
Hello Slackeramit,

Thanks for your reply. I tried to use the ECM.MVCTaxonomyPicker
but  ECM.MVCTaxonomyPicker  loose user selected terms on view reloaded in the case of Model state is invalid when the form is posted to server.  Pls treat it as urgent request. Thanks in advance for your help.

Regards

**Comment by khannsh** [comment]
Hello Amit,

The initial requirement was to let user enter/select Taxonomy values and then save the selected values in a list item.
We are using MVC. The taxonomy field is part of Model. In the Model I have declared the field as String instead of List<PickerTermModel>. As you have specified that you have used ECM.MVCTaxonomyPicker  and it is working fine. It would be really helpful if you can help resolve the issue that I specified in my previous comment.

Thanks & Regards

**Comment by khannsh** [comment]
Hello Paolo,

In the Partner pack I am updating Create site collection form to include 3 fields bind to termsets.
I am integrating the solution implemented by  ECM.MVCTaxonomyPicker . While integrating the solution I am facing following issue :-

**ECM.MVCTaxonomyPicker loose user selected terms on view reloaded in the case of Model state is invalid when the form is posted to server.** 

In the Model I am using `String` instead of  `List<PickerTermModel>`
Regards
Shival

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
