### ISSUE TITLE
Setup wizard azure login error : Calling principal cannot consent due to lack of permissions.

### ISSUE THREAD

**Issue by amirkhanRC** [SharePoint/PnP-Partner-Pack#253]
Hi again,
trying again the setup wizard but this time with my organizational account that proper rights in our company azure subscription to create resources.

when logging I get 
Calling principal cannot consent due to lack of permissions. error

trying to see how to consent the app from the o365 tenant as  tenant admin but I cannot see where. nor do I get prompted for consent at any time
help?

![image](https://cloud.githubusercontent.com/assets/20151481/24697437/74434572-19ed-11e7-958d-a2ae5ab6999c.png)

**Comment by PaoloPia** [comment]
You need to run the Setup Wizard using an account that is global admin for your tenant. It looks like your user is not able to consent the requested permissions due to a lack of permissions, like the error message states.

**Comment by PaoloPia** [comment]
Hi,
Were you able to run the wizard with proper user's permissions? In the meantime, I will close this item and I will re-open it in case of any further feedback.
