### ISSUE TITLE
Setup fail to login for Microsoft Azure

### ISSUE THREAD

**Issue by ravi-bamrotiya** [SharePoint/PnP-Partner-Pack#254]
Hello,
Setup is unable to login for Microsoft Azure it shows below screen.

![image](https://cloud.githubusercontent.com/assets/1353762/24751564/b9394e74-1ae7-11e7-990c-953a787ec6d8.png)

Error Text:
Additional technical information: 
Correlation ID: 653e53f2-a535-4d56-87d2-6361594bb340 
Timestamp: 2017-04-06 10:56:17Z 
AADSTS90093: Calling principal cannot consent due to lack of permissions.

**Could you please let me know what is the minimum permission required on Azure?**

**Comment by amirkhanRC** [comment]
Agreed. running into the same issue when working with various Azure subscriptions or if using an email address is both a personal and a work account.  A clear set of minimal requirements  would be very helpful when using  different accounts for the o365 and azure subscription (which paolo recommends in the video)
thank you

**Comment by ravi-bamrotiya** [comment]
Thanks @amirkhanRC,

Yes, I am using work or shcool(organisation) account

**Comment by PaoloPia** [comment]
Hi guys,
I will try to do my best to provide a list of requirements for setting up the PnP Partner Pack using the wizard. Stay tuned ...

**Comment by ravi-bamrotiya** [comment]
Thanks @PaoloPia 

As I am working in large organization so defiantly it would not be possible for me to get global admin role.

Thanks,
Ravi.
