### ISSUE TITLE
Unable to create publishing site

### ISSUE THREAD

**Issue by ravi-bamrotiya** [SharePoint/PnP-Partner-Pack#256]
Hello,

Unable to create site using base template CMSPUBLISHING#0 or BLANKINTERNET#0

Error: The web template CMSPUBLISHING#0 is not available for sites on this tenant.

**Comment by PaoloPia** [comment]
Hi,
So far the creation of a publishing site is not a use case covered by the PnP Partner Pack. I will keep this item open in case we will have time in the future to cover this scenario. Thanks for your feedback.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
