### ISSUE TITLE
error during setup null-valued expression

### ISSUE THREAD

**Issue by NaliTomar** [SharePoint/PnP-Partner-Pack#257]
I am getting an error during setup wonder if anyone can help.

[PnPSetUpError.txt](https://github.com/SharePoint/PnP-Partner-Pack/files/914736/PnPSetUpError.txt)
From line 43 in the Run.cs file it goes to line 52 catch exception.

Thanks in advanced.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We've already seen this kind of issue somewhere else and we are investigating for a bug. I will keep you updated. Thanks.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the PnP Partner Pack. I would suggest you to manually call the script MsBuildWebSite.ps1 providing the expected input parameters. Just to see what is failing in your environment. Then, please let me know. Thanks.

**Comment by NaliTomar** [comment]
Hi PaoloPia,
Thanks for your help.

I put a stop on run.cs line 23 to get the two parameters. 
The ProjectPath is "C:\\GitHub\\PnP-Partner-Pack-master\\OfficeDevPnP.PartnerPack.SiteProvisioning\\OfficeDevPnP.PartnerPack.SiteProvisioning"
The PublishingSettingsPath is "C:\\GitHub\\PnP-Partner-Pack-master\\OfficeDevPnP.PartnerPack.SiteProvisioning\\OfficeDevPnP.PartnerPack.SiteProvisioning\\pnp-partner-pack.publishingSettings"

When I bring up MsBuildWebSite.ps1 it did provide me with the -ProjectPath, but not the -PublishingSettingsPath marameter so I added the line pushd $PublishingSettingsPath right below pushd $ProjectPath, in which it then did. I am not sure if that was correct.

Running 
.\MsBuildWebSite.ps1 -ProjectPath "C:\\GitHub\\PnP-Partner-Pack-master\\OfficeDevPnP.PartnerPack.SiteProvisioning\\OfficeDevPnP.PartnerPack.SiteProvisioning" -PublishingSettingsPath "C:\\GitHub\\PnP-Partner-Pack-master\\OfficeDevPnP.PartnerPack.SiteProvisioning\\OfficeDevPnP.PartnerPack.SiteProvisioning\\pnp-partner-pack.publishingSettings"
did error, however. Attached is the output from the PowerShell consol. 

[MsBuildWebSite Error.txt](https://github.com/SharePoint/PnP-Partner-Pack/files/931346/MsBuildWebSite.Error.txt)

It seems that MsBuildWebSite.ps1 looks for information on my computer I don't have MSBuild v.14.0.

**Comment by NaliTomar** [comment]
Hi PaoloPia,

I think I found my problem.
I was using Visual Studio 2017. After installing Visual Studio 2015 the deployment completed.

Thanks for your help

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We found an issue in the setup wizard, when used within Visual Studio 2017. It is now fixed and you should be able to use both VS2015 or VS2017. I will close this item.
