### ISSUE TITLE
Error in Setup Wizard - Unblock File??

### ISSUE THREAD

**Issue by ThreadPitt** [SharePoint/PnP-Partner-Pack#258]
Hi,
I downloaded the newest version of the Partner Pack and the PnP PowerShell cmdlets, but the Wizard throws the following error (Windows Server 2012 R2, VS 2015, PowerShell 4):
I tried unblocking all the files with 

`Get-ChildItem -Path 'D:\PnP-Partner-Pack-master\OfficeDevPnP.PartnerPack.SiteProvisioning\OfficeDevPnP.PartnerPack.Setup\Scripts' -Recurse | Unblock-File`

but that didn't help either.

![error](https://cloud.githubusercontent.com/assets/11786803/25008059/d0bc80cc-2062-11e7-99f6-50046b910896.png)

Any hint is appreciated
Thx!

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the PnP Partner Pack. I would suggest you to manually call the script MsBuildWebSite.ps1 providing the expected input parameters. Just to see what is failing in your environment. Then, please let me know. Thanks.

**Comment by ThreadPitt** [comment]
Hi,
I finally got it working. In the end it turned out that the Windows Management Framework was missing: https://msdn.microsoft.com/en-us/powershell/wmf/5.0/requirements

After installation, the wizard ran through fine.

**Comment by PaoloPia** [comment]
Thanks for your feedback. I will close this item.
