### ISSUE TITLE
Azure WebJobs not working

### ISSUE THREAD

**Issue by chriswilper** [SharePoint/PnP-Partner-Pack#259]
I have used the wizard to install and configure the PnP Partner Pack but when I try and create a site collection I noticed that the job never completes.  When I navigate to Azure and click on web jobs and select the ContinousJob I see the following.

Continuous WebJob Details ContinousJob
ake sure that you are setting a connection string named AzureWebJobsDashboard in your Microsoft Azure Website configuration by using the following format DefaultEndpointsProtocol=https;AccountName=NAME;AccountKey=KEY pointing to the Microsoft Azure Storage account where the Microsoft Azure WebJobs Runtime logs are stored.

Please visit the article about configuring connection strings for more information on how you can configure connection strings in your Microsoft Azure Website.

The configuration is not properly set for the Microsoft Azure WebJobs Dashboard. 
In your Microsoft Azure Website configuration you must set a connection string named AzureWebJobsDashboard by using the following format DefaultEndpointsProtocol=https;AccountName=NAME;AccountKey=KEY pointing to the Microsoft Azure Storage account where the Microsoft Azure WebJobs Runtime logs are stored. 

Please visit the article about configuring connection strings for more information on how you can configure connection strings in your Microsoft Azure Website.

When I open the VS solution and look at the app.config file under the ContinousJob I see the following.  I replaced the AccountName with #############;

<connectionStrings>
    
    
    <add name="AzureWebJobsDashboard" connectionString="DefaultEndpointsProtocol=https;AccountName=#############;AccountKey=ZVkaAh8YEu2LxORTg3RRjpVkZ5wWXEYiaMglCsXfy0IiWNGaqj56COvIjfr6b+0UFz67ZcIDAjs+35M7qU3iGg==" />
    <add name="AzureWebJobsStorage" connectionString="DefaultEndpointsProtocol=https;AccountName=#############;;AccountKey=ZVkaAh8YEu2LxORTg3RRjpVkZ5wWXEYiaMglCsXfy0IiWNGaqj56COvIjfr6b+0UFz67ZcIDAjs+35M7qU3iGg==" />
  </connectionStrings>

**Comment by ThreadPitt** [comment]
Hi, 
I have the same problem: Ran the newest version, install worked fine, but when I create a site collection, it stays in "Pending" forever.
Furthermore, if I create a site collection without PnP and enable the Partner Pack using the Settings in PnP WebApp, I should get a "Save site as Template" in the settings of the Site Collection?

**Comment by ThreadPitt** [comment]
Plus: There is one Azure Jobs configured as "Continous". For that to work properly, the "Always On" feature of the App Service has to be enabled.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Please refer to this issue (https://github.com/SharePoint/PnP-Partner-Pack/issues/268) which gives you the answer to this question.
About the "Always On" feature, we will try to add it to the setup wizard.
