### ISSUE TITLE
Subsite creation fails when using template parameters

### ISSUE THREAD

**Issue by biste5** [SharePoint/PnP-Partner-Pack#264]
**Type:**
- [X] Bug

**Expected behavior:**
When creating a subsite with a template including `<pnp:Parameter>` elements; site should be successfully created, and values for parameters should be replaced.

**Observed behavior:**
site provisioning fails with error message
> Collection was modified; enumeration operation may not execute

**Steps to reproduce:**
Create a template that uses `<pnp:Parameter>` elements and tokens
Schedule the creation of a sub site with Partner Pack (ContinousJob).

**Steps to fix:**
The issue occurs in [SubSiteProvisioningJobHandler.cs#L148-L154](https://github.com/SharePoint/PnP-Partner-Pack/blob/dev/OfficeDevPnP.PartnerPack.SiteProvisioning/OfficeDevPnP.PartnerPack.Infrastructure/Jobs/Handlers/SubSiteProvisioningJobHandler.cs#L148-L154) because the collection is being modified (error is quite explicit, because it doesn't come from SharePoint 😄 )

In [SiteCollectionProvisioningJobHandler](https://github.com/SharePoint/PnP-Partner-Pack/blob/dev/OfficeDevPnP.PartnerPack.SiteProvisioning/OfficeDevPnP.PartnerPack.Infrastructure/Jobs/Handlers/SiteCollectionProvisioningJobHandler.cs) is implemented correctly so the same implementation should be reverted in SubSiteProvisioningJobHandler to fix this issue

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We will work on it.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your submission. We're sorry to inform you that we archived this repository and the PnP Partner Pack project will not be anymore supported. If you need to use something like that, we suggest you to move to the modern UI of SharePoint and to have a look at the SP Starter Kit (https://github.com/SharePoint/sp-starter-kit/).

If you still need to use and/or improve the PnP Partner Pack, you can download your own copy from this repository and work on that one.

Thanks for your support.
