### ISSUE TITLE
What is the minimum permission required to access the partner pack azure site?

### ISSUE THREAD

**Issue by ravi-bamrotiya** [SharePoint/PnP-Partner-Pack#265]
Hello,
I can access the partner pack azure site with global admin user but login gets failed for non admin users with below error message at sign in page.
" This application requires application permissions to another application. Consent for application permissions can only be performed by an administrator. Sign out and sign in as an administrator or contact one of your organization's administrators."

**Comment by biste5** [comment]
How did you setup Partner Pack?

You probably have missed the configuration step in AAD

> Click the Grant Permission button on the 'Required Permissions' tab, if you want to give non-tenant admin users access to the application.

From [PnP Partner Pack - Manual Setup Guide](https://github.com/SharePoint/PnP-Partner-Pack/blob/master/Documentation/Manual-Setup-Guide.md)

**Comment by ravi-bamrotiya** [comment]
Thank you @biste5 

I used setup wizard but your mentioned points worked for me.

**Comment by biste5** [comment]
you're welcome. It may be that the Setup Wizard doesn't include that step yet.
I normally do the setup manually still.

Maybe @PaoloPia or someone else can confirm the behavior of Setup Wizard, or if you'd encounter the same issue with a new installation using the wizard

**Comment by PaoloPia** [comment]
Hi,
thanks for your feedback. In theory, if you access the PnP Partner Pack site for the first time using a tenant Global Admin account, you should be prompted with the consent page and then the site should work for everybody else. We cannot "force" the consent at the setup level.
