### ISSUE TITLE
Using Responsive features, causes a JavaScript error in the Term Picker, which blocks the window

### ISSUE THREAD

**Issue by mrzyko** [SharePoint/PnP-Partner-Pack#266]
If you choose to create a site, and enables the responsive javascript, then it will cause an error in the Term Picker window. This is shown when you have a taxonomy sitecolumn, and want to add a value in the term field, then clicking the little icon that opens the term picker window, will not show anything. 
It is because sp-responsive-ui.js in the function setUpToggling, the line if (document.getElementById('navbar-toggle')) is not returning, as it is meant to.
I have changed mine to if (document.getElementById('navbar-toggle') == null) instead and now it works again.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. I moved the issue in the right repo (PnP-Sites-Core) because in the PnP Partner Pack we simply use Core to apply the Responsive UI capability. I will close this item.
