### ISSUE TITLE
PnP API Permissions

### ISSUE THREAD

**Issue by johnbrice** [SharePoint/PnP-Partner-Pack#267]
Currently trying to configure API permissions but am unable to find the APis for the items below. I simply cannot find these permissions or the APIs. Has something changed recently?

**Windows Azure Active Directory (Delegated Permission)**
Sign in and read user profile

**Office 365 SharePoint Online (Application Permission)**
Read and write managed metadata
Have full control of all site collection

So close, but so far. Can anyone shed any light on this?

**Comment by PaoloPia** [comment]
Hi,
the permissions can be configured in the Azure Active Directory management UI. If you are not confident with Azure AD and Azure in general, I would suggest you to use the new setup wizard, which will do all the setup process for you. Thanks.
