### ISSUE TITLE
Save Site as Provisoning Template/Create SubSite/Branding

### ISSUE THREAD

**Issue by johnbrice** [SharePoint/PnP-Partner-Pack#271]
I know this has been raised before as #212  but I can't resolve the issue.

The partner pack is enabled on a site collection but the save site template and the create sub-site links are not being updated. I have no errors in logs, continuous job is running, azurewebsiteurl is https:// to my app with trailing /

Im am not being redirected to the partner pack UI (I can see the pnp divs applied)

I am also unable to apply branding so I guess these must be linked. 

Hope someone can offer some advice :)

**Comment by jkovach82** [comment]
I am also not exactly clear how to extract a site template.  I have followed step 1 which is to go to PnP Settings and click Enable PnP Partner Pack on my target site.  I navigate to the site and nothing has changed with regards to the site as far as I can tell.

After I Enable PnP for my site, what is the next step to provision the site template?

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
