### ISSUE TITLE
Scripts have to be run from current path

### ISSUE THREAD

**Issue by Pieter-Veenstra** [SharePoint/PnP-Partner-Pack#272]
Currently the PnP site script gets a basePath using the following line:

```
# DO NOT MODIFY BELOW
$basePath = "$(convert-path ..)\OfficeDevPnP.PartnerPack.SiteProvisioning\OfficeDevPnP.PartnerPack.SiteProvisioning"

```

It would be better to use:

```
$path = Split-Path -parent $MyInvocation.MyCommand.Definition
$basePath = "$path\..\OfficeDevPnP.PartnerPack.SiteProvisioning\OfficeDevPnP.PartnerPack.SiteProvisioning"

```

With the above the script can be opened in PowerShell ISE (which doesn't set the current path) and the script will still run.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
