### ISSUE TITLE
Issue with creating Azure AD application

### ISSUE THREAD

**Issue by ramonitor** [SharePoint/PnP-Partner-Pack#277]
I'm having a problem with the setup not being able to properly create an Azure AD application. The CreateAzureApplication method failes to create the Azure AD application when calling the MakePostRequestForStringAsync method in the HttpHelper class. 

The exception that is being thrown is the following:

> {
  "error": {
    "code": "Request_BadRequest",
    "message": "The property 'value' does not exist on type 'Microsoft.DirectoryServices.KeyCredential'. Make sure to only use property names that are defined by the type.",
    "innerError": {
      "request-id": "087f77ed-c66c-4252-8268-a90acf5b0881",
      "date": "2017-06-13T08:43:13"
    }
  }
}

For this error there is no specific error handling in the RegisterAzureADApplication, so there is no indication things did go wrong in the GUI. 

Running the june 2017 release of PnP Partner Pack from within VS 2015 with update 3.

**Comment by gururaj-rk** [comment]
I am facing the same issue. The setup process completes rest of the steps but leaving the Azure web application unusable.+

**Comment by d3nnis0** [comment]
Facing the same issue as discribed above. As the registration of the AzureAD Application failes the settings in the webconfig are wrong.

**Comment by RobTeich** [comment]
Same here. Seems as if the logic covered by the Configure-Configs.ps1 is not being executed.

**Comment by rmorrison-greystone** [comment]
Confirming same issue here with June 2017 PnP. Seeing issue in both VS2015 and VS2017.

**Comment by RobTeich** [comment]
I managed to get the WebApp to deploy!!!
Needed to do the following:
1. Run the wizard with a new set of parameters (clean start) till it competed successfully. (took three tries of cleaning and rebuilding the package to get it to go all the way through.
2. Viewing this video on how to do the install manually (https://www.youtube.com/watch?v=ezWYorZClTI&feature=youtu.be)
3. Used the MMC to locate and export the SSL cert created by the set up wizard
4. Manually created the AzureAD App Registration as shown (including editing the manifest)
NOTE: I needed to add an "/" to the end of the reply URL for this to work properly.
5. Collecting info to populate the PowerShell command .\Configure-Configs.ps1 -AzureStorageAccountName "xxx" -AzureStoragePrimaryAccessKey "xxx" -ClientId "xxx" -ClientSecret "xxx" -ADTenant "csra.onmicrosoft.com" -CertificateThumbprint "xxx" -InfrastructureSiteUrl "xxx" and running it. This successfully set all the needed configs in the VS projects.
NOTE: Clinet Id = Registered App Id.
5. Locating the App Service and downloading the publishing profile (Get publish profile)
6 Publishing the Web App and then the WebJobs using this profile.

Hope this helps others get it set up and running.

**Comment by d3nnis0** [comment]
Investigated a little more time in debugging the behavior. 
As ramonitor already mentioned, the Graph API returns the following error when trying to create the Azure AD Application:

"error": {
"code": "Request_BadRequest",
"message": "The property 'value' does not exist on type 'Microsoft.DirectoryServices.KeyCredential'. Make sure to only use property names that are defined by the type."

When I modify the json and for example delete the KeyCredential definition, the api throws an other error regarding the property "StartDate" which does not exist...

To make it short: For me it seems that something changed on the Graph beta api which causes the issue.

**Comment by Jammybam** [comment]
I managed to deploy the webapp and provision the webjobs using the method RobTeich outlined 

To save you scrolling through the video, here is a link opening the video at the correct time position: [https://youtu.be/ezWYorZClTI?t=1205](url)

Thanks Rob!

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*

**Comment by itsyashpal** [comment]
As per the current implementation instead of value the attribute name should be key ..  After changing that now we are able to create the Azure AD application with cert authentication enabled
Please find the contract details for KeyCredential from below link  
https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/keycredential.md
