### ISSUE TITLE
Overload URL custom order form site creation settings on Sharepoint admin

### ISSUE THREAD

**Issue by LeoGoGarcia** [SharePoint/PnP-Partner-Pack#278]
Hello everyone, 

I'm trying to overload URL to point to PNP custom order form when users click "Create site" button but it's not working. 

I have this message:
"This content can’t be shown in a frame
There is supposed to be some content here, but the publisher doesn’t allow it to be displayed in a frame. This is to help protect the security of any information you might enter into this site."

BR, 

Leonardo

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
