### ISSUE TITLE
Sheduledjob

### ISSUE THREAD

**Issue by bmomtschilow** [SharePoint/PnP-Partner-Pack#281]
Hi,

afte having deployed the pnp partner pack I am  struggling with getting site published.
After having set the app.config and having also configured the same via Azure UI I get the following Error:
 WebJob Details ScheduledJob

Run command: OfficeDevPnP.PartnerPack.ScheduledJob.exe

Where do I have to run it ?

![fehler](https://user-images.githubusercontent.com/15086505/27677590-870973ea-5cb2-11e7-9ca8-d8335d2eb7b5.PNG)

**Comment by RobTeich** [comment]
I am having the same problem. It looks like everything got deployed properly. I was able to submit the job request to have a site provisioned. But, the job never seems to pick up the entry for processing.

**Comment by sharepointryan** [comment]
I too am experiencing this issue. I've deployed a brand new clean instance in my environment, but the scheduled job doesn't seem to work properly. The only way I've gotten it to run is by manually restarting the Azure App Service, which then lets me manually run the job (one time). That one run will work, but after that it will constantly fail regardless of settings.

**Comment by jkovach82** [comment]
Do you have the settings.job file with the cron settings.  ie 

{
  "schedule": "0 */10 * * * *"
}

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
