### ISSUE TITLE
Hiding existing action in site settings page

### ISSUE THREAD

**Issue by vicharerohan** [SharePoint/PnP-Partner-Pack#282]
Hi Team,
I need help to hide existing action in site settings page.

**Comment by HiltonGiesenow** [comment]
Which action do you mean? I've noticed that in subsites, it still has the "save site as template" command - is that the one?

**Comment by PaoloPia** [comment]
Hi,
Thanks for your submission. We're sorry to inform you that we archived this repository and the PnP Partner Pack project will not be anymore supported. If you need to use something like that, we suggest you to move to the modern UI of SharePoint and to have a look at the SP Starter Kit (https://github.com/SharePoint/sp-starter-kit/).

If you still need to use and/or improve the PnP Partner Pack, you can download your own copy from this repository and work on that one.

Thanks for your support.
