### ISSUE TITLE
People Picker with multiple principals

### ISSUE THREAD

**Issue by DennisJantos** [SharePoint/PnP-Partner-Pack#283]
It seems that the People Picker implementation in the PnP Partner only works with max one principal. If you allow multiple principals, you will get an issue with removing principals. The array of principals send to the server has invalid indexes. 

Did someone get the People Picker working with ASP.NET MVC with multiple principals enabled?

Thanks!
Dennis

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
