### ISSUE TITLE
SharePoint Site Collection Permissions Not Applied

### ISSUE THREAD

**Issue by jkovach82** [SharePoint/PnP-Partner-Pack#285]
I deployed the June v2 PnP solution and for some reason Primary and Secondary administrators always default to Company and SPO admin roles.  I have deployed older v2 solution and it does not have this issue, the HomeController.cs methods look almost identical in both solutions; only the new v2 June release has this issue.  Not sure exactly where to look for the problem, everything I see in both solutions look the same.

![pic](https://user-images.githubusercontent.com/20099972/28174573-b0a31482-67a6-11e7-9b31-ea6f899dcce3.png)

**Comment by Liba82** [comment]
Did you end up resolving this? I have a similar issue.
