### ISSUE TITLE
Register Azure AD app - Key Value Must be NULL in MANIFEST

### ISSUE THREAD

**Issue by marqueles** [SharePoint/PnP-Partner-Pack#287]
Hi,

When trying to update the manifest of the application in the Active Directory, it doesn´t accept the value of keyCredentials. A KeyValueMustBeNull Exception appears after trying to save the manifest.

When I try to access the azurewebsite, a 401 unauthorised appears, but contrary to the video, after some time the 401 error still appears.

Thanks,
Marcos

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
