### ISSUE TITLE
PnP Template Feature: Publishing Site - Hangs ScheduledJob Indefinately

### ISSUE THREAD

**Issue by jkovach82** [SharePoint/PnP-Partner-Pack#291]
When I create a Publishing Site via the ScheduledJob webjob in the App Service the job hangs on Site 04/12 - 33 - Features.  If I apply the same template via a console app using the same command the site template is applied in a matter of minutes.

Are there some dependencies either missing or outdated from the ScheduledJob project?  Or is this an App Service endpoint issue?

**Comment by tagacapiz** [comment]
I had the same experience that the job seems to get stuck in the Features but I waited, in my case it took almost 10 minutes to get to the next steps and successfully completed.
