### ISSUE TITLE
Governance - Sharepoint Branding job failing

### ISSUE THREAD

**Issue by Jammybam** [SharePoint/PnP-Partner-Pack#292]
Hi,

I'm attemtping to apply an alternative logo image across site collections, I have left the other fields - background image file URL, Color File URL, Font File URL, CSS Overrids File URL and UI Custom Actions File URL - empty. 

Shortly after clicking Roll Out, the job always fails with the following error:

Composed look 'SharePointBranding' can not be found; pass null or empty to set look directly (not based on an existing entry)

Is there something I'm doing wrong? Do those other fields need to be populated in order for the SharePoint Branding tool to work?

Any assistance would be greatly appreciated.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
