### ISSUE TITLE
Question: Does Partner Pack support Modern Sites and Pages?

### ISSUE THREAD

**Issue by ns8482e** [SharePoint/PnP-Partner-Pack#294]

**Comment by jkovach82** [comment]
Second this post, I modified the settings drop-down to include all sites and OneDrives and Modern sites error out when attempting to enable PnP settings on an existing site.  Would be good to provision modern sites via the engine and create templates.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the PnP Partner Pack. I'm sorry, but we do not support modern sites with the PnP Partner Pack.
