### ISSUE TITLE
Failed to save manifest. Error details: KeyValueMustBeNull

### ISSUE THREAD

**Issue by pondpikey** [SharePoint/PnP-Partner-Pack#297]
Raising this again, still seems to be an issue. I've logged it in azure portal. Becoming increasingly frustrated with this step. Has anyone managed to find a decent workaround for saving the manifest file?

"keyCredentials": [
    {
      "customKeyIdentifier": "2WIQFp3llmcoHyBXgjPNjRctl+8=",
      "keyId": "1fbf8022-3678-4855-a552-b2aa2316112b",
      "type": "AsymmetricX509Cert",
      "usage": "Verify",
      "value":  "MIIC9jCCAd6gAwI**omitted"
     }
  ],

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
