### ISSUE TITLE
When applying tenant branding Job failed

### ISSUE THREAD

**Issue by amitsaraswat83** [SharePoint/PnP-Partner-Pack#298]
Hi All,
when I try to create a site collection or a sub site with "Apply tenant branding" ON, I always get a Failed status with the details: Composed look 'SharePointBranding' can not be found; pass null or empty to set look directly (not based on an existing entry).

Any idea?
Regards,
Amit Saraswat

**Comment by HiltonGiesenow** [comment]
I'm just starting to play more with Partner Pack, and see this myself - I have a feeling it's because I've never actually -set- and Branding, which I'm guessing I would do using the "Governance" menu in the Partner Pack website. Maybe one of the main team can confirm/correct?

**Comment by PaoloPia** [comment]
Hi,
Thanks for your submission. We're sorry to inform you that we archived this repository and the PnP Partner Pack project will not be anymore supported. If you need to use something like that, we suggest you to move to the modern UI of SharePoint and to have a look at the SP Starter Kit (https://github.com/SharePoint/sp-starter-kit/).

If you still need to use and/or improve the PnP Partner Pack, you can download your own copy from this repository and work on that one.

Thanks for your support.
