### ISSUE TITLE
tenant.CreateSiteCollection issue :- Incorrect Primary SItecollection Administrator

### ISSUE THREAD

**Issue by khannsh** [SharePoint/PnP-Partner-Pack#302]
Hi,

We are using PnP Partner pack to provision site collections in our SP Online Tenant. 
For some of the users it is not seting the correct Primary site collection Administrator.
instead it is adding **Company Administrator** as Primary Site Collection Administrator and **SharePoint Service Administrator** as Secondary Site Collection Administrator which is **not correct**.

For Eg:- In one of such case we specified  abcdefg.hijklm.2@XXXX.XXXX.com as SiteOwnerLogin while provisioning site collection by using PnP Partner pack. Instead it added **Company Administrator** as Primary Site Collection Administrator and **SharePoint Service Administrator** as Secondary Site Collection Administrator which is **not correct**.

Kindly look into the issue . Will appreciate your quick help.

Thanks & Regards,
Shival

**Comment by khannsh** [comment]
One Update... 

There is no issue with the users belonging to **XXXXX.onmicrosoft.com** domain. 
But the issue is there if the users belongs to supplier.XXX.com or XXXX.com domain.
However there is no issue if we specify the same users as Site Administrator.

Request you to please treat this request as urgent.

Regards,

**Comment by PaoloPia** [comment]
Hi,
Thanks for your submission. We're sorry to inform you that we archived this repository and the PnP Partner Pack project will not be anymore supported. If you need to use something like that, we suggest you to move to the modern UI of SharePoint and to have a look at the SP Starter Kit (https://github.com/SharePoint/sp-starter-kit/).

If you still need to use and/or improve the PnP Partner Pack, you can download your own copy from this repository and work on that one.

Thanks for your support.
