### ISSUE TITLE
Problems with Setup 

### ISSUE THREAD

**Issue by rmillman** [SharePoint/PnP-Partner-Pack#307]
First, let me say thanks for all the hard work, this looks like some incredible stuff.

I am trying to deploy to my developer (msdn) instance using an onmicrosoft account.
I have both the Azure tenant and the O365 tenant.  I am using a trial subscription. (Finally figured that out).

When I run the setup program from VS 2017 Enterprise, I get the following problem:

Setup fails with deploying the provisioning templates
// Apply the templates to the target site
                    ApplyProvisioningTemplate(web, "Infrastructure", "PnP-Partner-Pack-Infrastructure-Jobs.xml");
                    ApplyProvisioningTemplate(web, "Infrastructure", "PnP-Partner-Pack-Infrastructure-Templates.xml");
                    ApplyProvisioningTemplate(web, "", "PnP-Partner-Pack-Infrastructure-Contents.xml");
None of the above lines work.
Traced down to Line 299 in Setup Manager.cs, actual failure occurs on 
web.ApplyProvisioningTemplate(template, ptai);

Error Response:
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at OfficeDevPnP.PartnerPack.Setup.ViewModel.MainViewModel.<Setup>b__146_0() in C:\pnp\PnP-Partner-Pack\OfficeDevPnP.PartnerPack.SiteProvisioning\OfficeDevPnP.PartnerPack.Setup\ViewModel\MainViewModel.cs:line 450
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

Inner Exception 1:
ServerUnauthorizedAccessException: Access denied. You do not have permission to perform this action or access this resource.

Not sure why I wouldn’t have access.
I was able to create the site collection using the same account through setup, it is failing at the deploying of the templates.

I'd love some pointers on where to look.  Not sure what is going wrong.

**Comment by ohaak** [comment]
Same problem here. Testet on two different tenants. Not sure what exactly is "unauthorized" here. As we are working with tenant admin permission it's probably somethig regarding the app permissions for the setup wizard itself.

**Comment by lee-anne** [comment]
ditto, Is there workaround please?

**Comment by spsguru** [comment]
Add my voice to the chorus. I can successfully though the wizard create the infrastructure site collection, but it will not process and implement the pnp templates for the infrastructure site collection, so the SC is just an OOB SC. And this blocks the rest of the wizard process, so just manually applying the pnp template won't work here. 

Seems like some issue specifically with either accessing the XML template files, or with OfficeDevPNP.Core  ApplyProvisioningTemplate.

@PaoloPia , any ideas?

**Comment by spsguru** [comment]
Ok I can confirm from debug output that it does load up the first provisioning template .xml file, and then it throws the Microsoft.SharePoint.Client.ServerUnauthorizedAccessException .

**Comment by PaoloPia** [comment]
Hi,
We figured out where the issue is. Now we need to fix it :-) ... stay tuned, and thanks for the feedback.

**Comment by spsguru** [comment]
Thanks! And I'd be more than happy to test it out, if I can help. The wizard is a really great addition to the Partner pack.

**Comment by PaoloPia** [comment]
Just a quick update on this: we fixed the issue on our side, and few more issues related to some schema changes that occurred to the beta endpoint of the MSGraph. However, there is still one open bug that came out while creating a new application in Azure AD, using the /beta/applications endpoint of the MSGraph, and that we cannot fix autonomously. Most likely we will be able to fix it in the upcoming weeks, as soon as we'll get an answer or much more details from the Graph team. Stay tuned ...

**Comment by HiltonGiesenow** [comment]
In the meantime, you can use the PowerShell + manual guidance to do the setup, of course, it's just a lot of work

**Comment by JeffGSparks** [comment]
I ran this today and while the wizard makes it through without any exceptions, ultimately the Web App in Azure returns a 500 error. Whether related or not I also see that the app was not completely created within Azure AD as well.  I'm hoping that this what you're working on in relation to the Graph issue Paolo mentioned a couple of weeks back.

Best of luck, this looks like good stuff. Hoping to try it soon. Thanks!

**Comment by PaoloPia** [comment]
Hi,
Thanks for your submission. We're sorry to inform you that we archived this repository and the PnP Partner Pack project will not be anymore supported. If you need to use something like that, we suggest you to move to the modern UI of SharePoint and to have a look at the SP Starter Kit (https://github.com/SharePoint/sp-starter-kit/).

If you still need to use and/or improve the PnP Partner Pack, you can download your own copy from this repository and work on that one.

Thanks for your support.
