### ISSUE TITLE
Composed theme did not apply

### ISSUE THREAD

**Issue by imir-hoxha** [SharePoint/PnP-Partner-Pack#324]
I created a site collection and I changed the theme via the UI. Just giving a different theme which comes OOTB.

I saved the site as a template via the PnP page and then I created a new site collection via this template. What I saw is that the theme was not applied and two aspx pages were not copied.

Normally only the index page is copied, but why isn't the theme applied? Is there a switch somewhere which I need to turn on?

**Comment by HiltonGiesenow** [comment]
I'm kinda new to the partner pack, so just trying to help, not sure if this will be useful of not.

Remember that the Partner Pack is just relying on the PnP Provisioning stuff under the covers so anything it's doing you can try troubleshoot more directly yourself, say using the PnP Powershell (https://github.com/SharePoint/PnP-PowerShell). For instance, you might want to download the .pnp file and try apply it manually to the new site to see what's going on using Apply-PnPProvisioningTemplate, or try create the PnP template directly yourself using Get-PnPProvisioningTemplate, which gives some additional switches you can set, such as PersistPublishingFiles which I think would take the aspx pages.

Once it's all working, you could simply replace the .pnp file in the Infrastructure site collection with the new version, and create sites as usual using that.

**Comment by slimman** [comment]
I have actually tried via powershell and I even used the OfficeDevPnP.Core solution and debugged the code, but still can't seem to get the theme exported and imported.

It still applies the red background on the top ribbon of Office 365.

I used both these switches PersistBrandingFiles = true; PersistPublishingFiles = true; but still can't get it to work as they show in the video.

It is a bit difficult to understand all that code and I am just wasting time with something that could be very simple.

**Comment by HiltonGiesenow** [comment]
If this is O365, is this a Classic team site or a new "Modern" style one? If it's Modern, (e.g. maybe you're creating a template from Classic but trying to apply it to Modern) then I don't think it'll work. If it's classic though, then send me a link to the template and I'll try it out my side and let you know if I have any luck.

**Comment by slimman** [comment]
Hi Hilton, it is a classic site being applied to a classic site.
I have added a few client-site spfx extensions, just to give it a try and see if they will be copied.
You can try it directly from this site: https://alisaemily.sharepoint.com/sites/newsite2
user:user100@alisaemily.onmicrosoft.com
Pass: Xug54841

Let me know what you get.

**Comment by HiltonGiesenow** [comment]
I can access the site ok, but I'd like to try the template itself. Do you have a way to get the .pnp file to me? Maybe just drop it in a library on the site you sent :-). I'll try it my side and see if I can see anything obvious, but another suggestion is to try turn the PnP logging on for the provisioning engine

**Comment by slimman** [comment]
I have uploaded a zipped file in the Documents library. The zip contains the pnp template. 
Thanks a lot for your help.

**Comment by HiltonGiesenow** [comment]
ah I didn't keep the login details. You can mail me directly - firstname at lastname dot com

**Comment by slimman** [comment]
Hold on I will put it back.

**Comment by slimman** [comment]
user100@alisaemily.onmicrosoft.com
Woh25397
https://alisaemily.sharepoint.com/sites/newsite2

**Comment by HiltonGiesenow** [comment]
got it

**Comment by slimman** [comment]
Normally I when I put .zip at the end of the file ".pnp" I can open the and see the files inside, but this time it does not open it. It throws an error.

**Comment by slimman** [comment]
I have uploaded another pnp file: template1.pnp. Could you please download this as well? Thanks.

**Comment by HiltonGiesenow** [comment]
In this case it's generating the xml directly (i.e. not the "zip" with the xml inside it) - the pnp is in fact an xml, if that's more clear. That explains why it's not bundling anything in. What version of PNP are you using locally, and what command are you using? Also, it seems like this is purely a provisioning issue, not "partner pack" related - you might find more luck/help on the main PnP issue list (more than just little old me :->)

**Comment by HiltonGiesenow** [comment]
I've got the login details by the way, you can delete the u+p message above again

**Comment by slimman** [comment]
Ah, yes. I get it now why it does not open as it is an xml file with the pnp extension. I renamed the file to xml and it opened. I thought it was a zip file (pnp) and was supposed to contain the artifacts inside.

I have the latest pnp solution which I have taken from the github (here).

**Comment by slimman** [comment]
![tessss](https://user-images.githubusercontent.com/36191396/36415428-c57ba1c8-161d-11e8-8be2-25e2e729f013.png)

The site was provisioned, but 
1) it does not copy all the aspx files
2) it has inserted the header and footer twice (see attached image)

**Comment by slimman** [comment]
As the issue with the zip file, this is what I did wrong I think:
I renamed the extension of the file in the code from xml to pnp. 

				// We can also serialize this template for future usage if we want, not really needed
				XMLTemplateProvider provider = new XMLFileSystemTemplateProvider(@"c:\temp\pnpprovisioningdemo", "");
				provider.SaveAs(template, **"PnPProvisioningDemo.pnp");**

				return template;

**Comment by slimman** [comment]
OK, thanks a lot for your help. It is still a headache going through all the code and trying to understand what it does.

I changed the theme of the source site to black background, but it did not get applied to the target site.
and it still inserts the header and footer twice. I will check the pnp file to learn more from.

**Comment by HiltonGiesenow** [comment]
sorry I couldn't help more. At least you know where to look now. One possible tip - some of this stuff is easier to do from PowerShell (PnP PowerShell project) so maybe give that a try if you're flipping between a bunch of things, might be faster

**Comment by slimman** [comment]
thanks for the tip and your help.
