### ISSUE TITLE
Notebook link does not work. it throws an error

### ISSUE THREAD

**Issue by imir-hoxha** [SharePoint/PnP-Partner-Pack#325]
After a site is created from a template, the notebook link on left navigation does not work.

**Comment by HiltonGiesenow** [comment]
I'd suggest the same answer as to your other question (https://github.com/SharePoint/PnP-Partner-Pack/issues/324), at least to get this working (or at the very least to try find out more of what's going wrong) - save the template manually using PnP PowerShell and have a look at the xml template to see if that link looks correct or not. Worst case you'll be able to post more info into here to help the team troubleshoot (or submit a PR yourself :->)
