### ISSUE TITLE
Microsoft.IdentityModel.Protocol.Extensions

### ISSUE THREAD

**Issue by joelfmrodrigues** [SharePoint/PnP-Partner-Pack#326]
I was getting the following error after deploying the project:

"Could not load file or assembly ‘Microsoft.IdentityModel.Protocol.Extensions’ or one of its dependencies. The located assembly’s manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"

I have managed to resolve it by updating the relevant nugget package to the latest version. Should I submit a PR with the new version?

Thanks,
Joel

**Comment by HiltonGiesenow** [comment]
Joel, did you have to make any code changes? I seem to recall having some trouble recently, I think with some of the Exception types, but I didn't document it at the time.

**Comment by joelfmrodrigues** [comment]
No, just update the package version

**Comment by virtualducttape** [comment]
As another data point, I also got this error, and resolved it by updating the 'Microsoft.IdentityModel.Protocol.Extensions' nuget package.
