### ISSUE TITLE
Enabling PnP Partner Pack in a Site Collection fails in the PnP Site

### ISSUE THREAD

**Issue by HiltonGiesenow** [SharePoint/PnP-Partner-Pack#327]
If I go to the /Home/Settings page to try enable the Partner Pack on a Site Collection, it does nothing and eventually times out (it gets to 
```context.Site.RootWeb.ApplyProvisioningTemplate(template, ptai);``` in ```ApplyProvisioningTemplateToSite``` method in PnPPartnerPackUtilities.cs).

It works fine if I run the command from PowerShell directly using ```Enable-PnPResponsiveUI``` and giving it the path to the infrastructure site collection, and many other operations are working in the website (like it gets a list of templates from the infrastructure site collection, it shows me the site collections that I can enable/disable partner pack, etc.). I can even use this same page to *disable* the partner pack - that works fine, it just won't do the initial *enable*.

Anyone got any suggestions?

**Comment by spsguru** [comment]
I'm seeing the same behavior, and it appears to be similar to the other issue from earlier in late January, as the difference between enabling and disabling the partner pack in a SC is that enabling requires an Apply Template action, while disabling does not. So We still need to figure out why templates getting applied.

**Comment by HiltonGiesenow** [comment]
Yup, "disable" just hits the site directly and resets what's needed. An option, if there's no way to fix this for some reason, is to pop a message onto the queue to turn this on as if it was any other kind of template, but it shouldn't be required.

**Comment by spsguru** [comment]
Well, right now, I'm seeing it as it is not applying any template - even when creating a subweb, it creates the subweb, but not applying the PnP template.So, working through that right now, and I feel like if I can resolve it, then the enable PnP will start working too.

**Comment by HiltonGiesenow** [comment]
that might be the jobs not running as planned. To verify, you can try run them by hand from within Visual Studio (either by running the projects, or by executing the webjobs in the Azure sidebar)

**Comment by spsguru** [comment]
Update on this: So I have verified that jobs are executing and completing successfully, and even on subweb creation templates are being applied, it seems it is only the enabling of the PnP on a site collection (using the PnP-Partner-Pack-Overrides.xml partial template). No obvious errors though, it just stalls and doesn't apply it.

**Comment by HiltonGiesenow** [comment]
Yup, that's exactly my behaviour too - it eventually just times out. It's strange because everything else works, and it's got rights to access SPO to get the site list, load the template itself, etc. Thanks for verifying, hopefully the core team have some ideas.
