### ISSUE TITLE
Is there a roadmap for this project?

### ISSUE THREAD

**Issue by rroman81** [SharePoint/PnP-Partner-Pack#333]
I am just getting back into O365 and SPO work again and noticed that this project is still kicking well.  I was wondering if there is a road map to some of the features enhancements?

**Comment by VesaJuvonen** [comment]
We are gradually archiving this project as it is replaced with the SP Starter Kit for modern experiences. You can find more information on that from https://github.com/SharePoint/sp-starter-kit.
